### ISSUE TITLE
serve-placeholder should not check for query param

### ISSUE THREAD

**Issue by gaoyuan123** [nuxt/serve-placeholder#17]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[http://egame.qq.com/?ADTAG=g.map](http://egame.qq.com/?ADTAG=g.map)

### Steps to reproduce

打开http://egame.qq.com/?ADTAG=g.map 返回404
打开http://egame.qq.com/?ADTAG=g 正确返回

serve-placeholder组件处理url时没有正确处理查询参数，导致查询参数命中规则

> The serve-placeholder component does not correctly process the query parameters when processing the url, resulting in query parameter hit rules.

### What is expected ?

正确返回

> Return correctly

### What is actually happening?

返回404

> Return 404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8820">#c8820</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks, @gaoyuan123 for the report. Would you please manually add `serve-placeholder@^1.2.1` to your project to confirm this bug is fixed on your side?
