### ISSUE TITLE
NPM audit issue with the defaults-deep package

### ISSUE THREAD

**Issue by enddevNZ** [nuxt/serve-placeholder#7]
<img width="614" alt="screen shot 2019-02-07 at 3 27 26 pm" src="https://user-images.githubusercontent.com/47286332/52390868-c360e100-2aee-11e9-9eb8-729fcb63b859.png">

While running npm audit on recent nuxt setup there was an issue shown with the package default deep. currently shows no updated fix for that package. 

[https://www.npmjs.com/advisories/778](url)

**Comment by pi0** [comment]
Thanks, @enddevNZ for the report. Working on it. (jonschlinkert/defaults-deep#5)

**Comment by McLeodUA** [comment]
Any updates so far?
